### ISSUE TITLE
One should install recommends and only in exceptional cases one should choose not to

### ISSUE THREAD

**Issue by diederikdehaas** [CounterPillow/quartz64-images#3]
I just saw the following in ``debos-recipes/debian-quartz64.yaml``:
```
  - action: apt
    description: Install base packages
    recommends: false
    packages:
      - <long package list>
```
And I doubt that ``recommends: false`` is what you would/should want.

Recommends in Debian are like soft dependencies: *technically* they are not **required** for the package which recommends them to function **at all**, but in ~ 99% of cases you really want them. Therefor they are installed by default.

You can choose/determine that in specific cases you do not want/need them and then you would install *that particular package* without recommends. But especially in scripts/recipes like this, you should clearly document that (in code or (separate) commit message).

But in the above code snippet, it gets done for all packages, without an explanation as to why.
I think one should NOT do that.
